### Verbo GET – listar
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar com id
GET http://localhost:8000/produto/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "Cristina",
    "preco" : 23.50,
    "qtd" : 20,
    "descricao" : "Descrição aleatória",
    "foto": "umafoto"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Put Produto",
    "preco" : "23.50",
    "qtd" : "20",
    "descricao" : "Descrição aleatória",
    "foto": "uma foto2"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1