### Verbo GET – listar
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar com id
GET http://localhost:8000/cliente/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Abc da Silva",
    "cpf" : "01923874656",
    "telefone" : "49988234567",
    "login" : "meu_login",
    "senha" : "bolinhas",
    "matricula" : "12345",
    "pega_fiado" : 1
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/1 HTTP/1.1
content-type: application/json

{
    "nome" : "Bolinhas dos Testes",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "login" : "meu_login",
    "senha" : "a",
    "matricula" : "12345",
    "pega_fiado" : 2
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/1 HTTP/1.1